### ISSUE TITLE
Error generating new project

### ISSUE THREAD

**Issue by MadOtis** [pusongyang/generator-fullstack-backbone#2]
Hello,

I just installed the latest version of the generator and can't get past creating a new project.  I've installed yo, grunt, gulp, etc. and try to run the generator to create a new project, and it fails as shown here:

```
MYMAC:CMDB2 madotis$ yo fullstack-backbone CMDB2
undefined
Out of the box I include HTML5 Boilerplate, jQuery and Backbone.js.
? What more would you like?
? which UI framework would you like? Twitter Bootstrap for Sass
? what's your default entry file's name? index.html
? what's your default server route name? api
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/generator-fullstack-backbone/generators/app/templates/app/images'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at Function.sync (/usr/local/lib/node_modules/generator-fullstack-backbone/node_modules/mkdirp/index.js:71:13)
    at yeoman.generators.Base.extend.writing.setupEnv (/usr/local/lib/node_modules/generator-fullstack-backbone/generators/app/index.js:293:20)
    at /usr/local/lib/node_modules/generator-fullstack-backbone/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

If it helps, I'm on a MAC (10.10.5) with node.js 5.4.1

Any ideas where to turn?

**Comment by pusongyang** [comment]
I got this error before. It happens on MAC.
You need create this fold manual.
sudo mkdir /usr/local/lib/node_modules/generator-fullstack-backbone/generators/app/templates/app/images

**Comment by pusongyang** [comment]
update:
you can update generator-fullstack-backbone，new patch will keep the images folder.
